companies = [
    {"company": "3R Petroleum ON", "url": "https://br.investing.com/equities/3r-petroleum-oleo-e-gas-sa"},
    {"company": "Alpargatas PN", "url": "https://br.investing.com/equities/alpargatas-pn-n1"},
    {"company": "Allos ON", "url": "https://br.investing.com/equities/aliansce-on-nm"},
    {"company": "Ambev ON", "url": "https://br.investing.com/equities/ambev-pn"},
    {"company": "Arezzo ON", "url": "https://br.investing.com/equities/arezzo-co-on-ej-nm"},
    {"company": "Assaí ON", "url": "https://br.investing.com/equities/sendas-distribuidora-sa"},
    {"company": "Azul PN", "url": "https://br.investing.com/equities/azul-sa-pref"},
    {"company": "B3 ON", "url": "https://br.investing.com/equities/bmfbovespa-on-nm"},
    {"company": "Banco do Brasil ON", "url": "https://br.investing.com/equities/brasil-on"},
    {"company": "BB Seguridade ON", "url": "https://br.investing.com/equities/bbseguridad"},
    {"company": "Bradesco ON", "url": "https://br.investing.com/equities/bradesco-on-n1"},
    {"company": "Bradesco PN", "url": "https://br.investing.com/equities/bradesco-pn-n1"},
    {"company": "Bradespar PN", "url": "https://br.investing.com/equities/bradespar-pn-n1"},
    {"company": "BRF ON", "url": "https://br.investing.com/equities/brf-foods-on-ej-nm"},
    {"company": "Braskem PN", "url": "https://br.investing.com/equities/braskem-pna-n1"},
    {"company": "BTG Pactual Unit", "url": "https://br.investing.com/equities/banco-btg-pactual-sa"},
    {"company": "Carrefour ON", "url": "https://br.investing.com/equities/atacadao-sa"},
    {"company": "CCR ON", "url": "https://br.investing.com/equities/ccr-sa-on-nm"},
    {"company": "Cemig PN", "url": "https://br.investing.com/equities/cemig-pn-n1"},
    {"company": "Centrais Eletricas Brasileiras", "url": "https://br.investing.com/equities/eletrobras-on"},
    {"company": "Centrais Eletricas Brasileiras Prf", "url": "https://br.investing.com/equities/eletrobras-pnb"},
    {"company": "Cielo ON", "url": "https://br.investing.com/equities/cielo-on-nm"},
    {"company": "Cogna ON", "url": "https://br.investing.com/equities/kroton-on-nm"},
    {"company": "COPEL PNB", "url": "https://br.investing.com/equities/copel-pnb"},
    {"company": "Cosan ON", "url": "https://br.investing.com/equities/cosan-on-nm"},
    {"company": "CSN Mineração ON", "url": "https://br.investing.com/equities/csn-mineracao"},
    {"company": "CSN ON", "url": "https://br.investing.com/equities/sid-nacional-on"},
    {"company": "CVC Brasil ON", "url": "https://br.investing.com/equities/cvc-brasil-on"},
    {"company": "Cyrela ON", "url": "https://br.investing.com/equities/cyrela-realt-on-nm"},
    {"company": "Dexco ON", "url": "https://br.investing.com/equities/duratex-on-nm"},
    {"company": "Energisa Unit", "url": "https://br.investing.com/equities/energisa-sa"},
    {"company": "Engie Brasil ON", "url": "https://br.investing.com/equities/tractebel-on-nm"},
    {"company": "Eneva ON", "url": "https://br.investing.com/equities/eneva-sa"},
    {"company": "Equatorial ON", "url": "https://br.investing.com/equities/equatorial-on-nm"},
    {"company": "Estácio Part ON", "url": "https://br.investing.com/equities/estacio-part-on-nm"},
    {"company": "Embraer ON", "url": "https://br.investing.com/equities/embraer-on-nm"},
    {"company": "Eztec ON", "url": "https://br.investing.com/equities/eztec-on-nm"},
    {"company": "Fleury ON", "url": "https://br.investing.com/equities/fleury-on-nm"},
    {"company": "Gerdau PN", "url": "https://br.investing.com/equities/gerdau-pn-n1"},
    {"company": "Grupo Soma ON", "url": "https://br.investing.com/equities/grupo-de-moda-soma-sa"},
    {"company": "Hypera ON", "url": "https://br.investing.com/equities/hypermarcas-sa?cid=18698"},
    {"company": "Iguatemi Unit", "url": "https://br.investing.com/equities/iguatemi-unt"},
    {"company": "Itaúsa PN", "url": "https://br.investing.com/equities/itausa-pn-ej-n1"},
    {"company": "Itaú Unibanco PN", "url": "https://br.investing.com/equities/itauunibanco-pn-edj-n1"},
    {"company": "IRB Brasil ON", "url": "https://br.investing.com/equities/irb-brasil-resseguros"},
    {"company": "JBS ON", "url": "https://br.investing.com/equities/jbs-on-nm"},
    {"company": "Klabin Unit", "url": "https://br.investing.com/equities/klabin-unt"},
    {"company": "Localiza ON", "url": "https://br.investing.com/equities/localiza-on-ej-nm"},
    {"company": "Lojas Renner ON", "url": "https://br.investing.com/equities/lojas-renner-on-nm"},
    {"company": "Lwsa", "url": "https://br.investing.com/equities/locaweb-servicos-de-internet-sa"},
    {"company": "Magazine Luiza ON", "url": "https://br.investing.com/equities/magaz-luiza-on-nm"},
    {"company": "Marfrig ON", "url": "https://br.investing.com/equities/marfrig-on-nm"},
    {"company": "Metalúrgica Gerdau PN", "url": "https://br.investing.com/equities/gerdau-met-pn"},
    {"company": "Minerva ON", "url": "https://br.investing.com/equities/minerva-on-nm"},
    {"company": "MRV ON", "url": "https://br.investing.com/equities/mrv-on-nm"},
    {"company": "Multiplan ON", "url": "https://br.investing.com/equities/multiplan-on-n2"},
    {"company": "Natura ON", "url": "https://br.investing.com/equities/natura-on-nm"},
    {"company": "Petrobras ON", "url": "https://br.investing.com/equities/petrobras-on"},
    {"company": "Petrobras PN", "url": "https://br.investing.com/equities/petrobras-pn"},
    {"company": "Petrorecôncavo ON", "url": "https://br.investing.com/equities/petroreconcavo"},
    {"company": "Petz ON", "url": "https://br.investing.com/equities/pet-center-comercio-e-partcipacoes"},
    {"company": "Pão de Açúcar ON", "url": "https://br.investing.com/equities/companhia-brasileira-de-distribuica"},
    {"company": "Prio ON", "url": "https://br.investing.com/equities/hrt-petroleo-on-nm"},
    {"company": "Raia Drogasil ON", "url": "https://br.investing.com/equities/raiadrogasil-on-nm"},
    {"company": "Raizen PN", "url": "https://br.investing.com/equities/raizen-prf"},
    {"company": "Rede D'Or ON", "url": "https://br.investing.com/equities/rede-dor-sao-luiz"},
    {"company": "Rumo ON", "url": "https://br.investing.com/equities/all-amer-lat-on-nm"},
    {"company": "Sabesp ON", "url": "https://br.investing.com/equities/sabesp-on"},
    {"company": "Santander Brasil Unit", "url": "https://br.investing.com/equities/santander-br-unt-ed-n2"},
    {"company": "SLC Agrícola ON", "url": "https://br.investing.com/equities/slc-agricola-on-nm"},
    {"company": "São Martinho ON", "url": "https://br.investing.com/equities/sao-martinho-on-nm"},
    {"company": "Suzano ON", "url": "https://br.investing.com/equities/suzano-papel-celulose"},
    {"company": "Taesa Unit", "url": "https://br.investing.com/equities/taesa-unt-n2"},
    {"company": "Telefônica Brasil ON", "url": "https://br.investing.com/equities/telef-brasil-on"},
    {"company": "TIM ON", "url": "https://br.investing.com/equities/tim-part-s-a-on-nm"},
    {"company": "Totvs ON", "url": "https://br.investing.com/equities/totvs-on-ej-nm"},
    {"company": "Transmissão Paulista PN", "url": "https://br.investing.com/equities/tran-paulist-pn"},
    {"company": "Ultrapar ON", "url": "https://br.investing.com/equities/ultrapar-on-nm"},
    {"company": "Usiminas PNA", "url": "https://br.investing.com/equities/usiminas-pna"},
    {"company": "Vale ON", "url": "https://br.investing.com/equities/vale-on-n1"},
    {"company": "Vamos ON", "url": "https://br.investing.com/equities/grupo-vamos-sa"},
    {"company": "Vibra ON", "url": "https://br.investing.com/equities/petrobras-distribuidora"},
    {"company": "Vivara ON", "url": "https://br.investing.com/equities/vivara-participacoes-sa"},
    {"company": "Weg ON", "url": "https://br.investing.com/equities/weg-on-ej-nm"},
    {"company": "YDUQS ON", "url": "https://br.investing.com/equities/estacio-part-on-nm"}
]